version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - dependencies
    groups:
       dev-dependencies:
          patterns:
            - "*"  

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - dependencies
    groups:
       docker-dependencies:
          patterns:
            - "*"  
